services:
  database:
    image: postgres:17.6-alpine3.22
    container_name: products-db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
